
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["PopcartSeller/PopcartSeller.csproj", "PopcartSeller/"]
RUN dotnet restore "PopcartSeller/PopcartSeller.csproj"
COPY . .
WORKDIR /src/CecyApi
RUN dotnet build "PopcartSeller.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PopcartSeller.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PopcartSeller.dll"]
